name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  release:
    name: publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Publish
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}